on:
  push:
    branches:
      - DEV
concurrency:
  group: DEV
  cancel-in-progress: true
name: 🚀 Deploy DEV to Vercel Server
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy DEV
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.vercel.com/v1/integrations/deploy/prj_ffKhXzkKnbYjWviEdF3d9m0bAokg/XIilCkOHyV'
        method: 'GET'
