on:
  push:
    branches:
      - master
concurrency:
  group: master
  cancel-in-progress: true
name: 🚀 Deploy master to Vercel Server
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy master
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.vercel.com/v1/integrations/deploy/prj_ffKhXzkKnbYjWviEdF3d9m0bAokg/siEaj5uawU'
        method: 'GET'
